- name: install
  command: "{{ bower_cmd }} install {{ pkg }}"
  # command: "echo \"{{ bower_cmd }} install {{ name }}\""
  when: state == 'present'

- name: uninstall
  command: "{{ bower_cmd }} uninstall {{ pkg }}"
  when: state == 'absent'
